### ISSUE TITLE
City not available

### ISSUE THREAD

**Issue by bdollerup** [PiotrMachowski/Home-Assistant-custom-components-Antistorm#11]
Hi there,

I can't find Copenhagen, Denmark in there. Since the service is using a .eu suffix, I would assume you are supporting all EU countries, is this a correct assumption?

Thanks,
/// Bjarne

**Comment by PiotrMachowski** [comment]
Hi @bdollerup 

Unfortunately Antistorm provides data only for Poland

Regards,
Piotr
