### ISSUE TITLE
Antistorm sensory niedostępne

### ISSUE THREAD

**Issue by nawonpl** [PiotrMachowski/Home-Assistant-custom-components-Antistorm#19]
Od kilku dni sensory antistorm są niedostępne a strona antistorm nie działa. Czy wiadomo co się stało?

**Comment by PiotrMachowski** [comment]
U mnie wszystko działa...

**Comment by nawonpl** [comment]
To był problem u mojego operatora światłowodu

**Comment by PiotrMachowski** [comment]
W porządku, wszystko jasne

**Comment by PiotrMachowski** [comment]
@nawonpl byłbyś w stanie powiedzieć coś więcej? Jak rozwiązałeś ten problem, jakiego masz operatora? Napisała do mnie kolejna osoba z dokładnie taką samą sytuacją

**Comment by nawonpl** [comment]
Mam internet światłowodowy od tmobile. Antistorm był jedyną stroną która nie działała więc sądziłem że problem jest u nich. Próbowałem wielu rozwiązań ale pomógł dopiero restart routera tmobile i pewnie otrzymanie nowego ip.

**Comment by PiotrMachowski** [comment]
Ok, czyli brzmi jak ban na Twoje IP. Czy robiłeś np. wiele restartów HA zanim dostałeś bana?

**Comment by nawonpl** [comment]
Mogłem zrobić dwa restarty z rzędu przy zmienianiu konfiguracji.

**Comment by PiotrMachowski** [comment]
ok, dzięki za info
