### ISSUE TITLE
Cannot find the station_id

### ISSUE THREAD

**Issue by InToSSH** [PiotrMachowski/Home-Assistant-custom-components-Antistorm#2]
Hi,
I checked the antistorm.eu page, found the widget page, but in the details it only shows the lat/log position, not the station_id. Where can I please find it?

**Comment by PiotrMachowski** [comment]
You have to use a generator from a developers section (as linked in a README).
![image](https://user-images.githubusercontent.com/6118709/74205488-debd7980-4c77-11ea-8839-96eebfcb57c9.png)
