### ISSUE TITLE
[HA 0.110.0]: BinarySensorDevice is deprecated

### ISSUE THREAD

**Issue by andriej** [PiotrMachowski/Home-Assistant-custom-components-Antistorm#8]
Latest HA, during startup error is thrown:
Logger: homeassistant.components.binary_sensor
Source: components/binary_sensor/__init__.py:174
Integration: Sensor binarny (documentation, issues)
First occurred: 10:53:37 (4 occurrences)
Last logged: 10:53:37

BinarySensorDevice is deprecated, modify AntistormBinarySensor to extend BinarySensorEntity

![image](https://user-images.githubusercontent.com/6303489/82427266-20d13500-9a89-11ea-8717-aff11f45c270.png)

**Comment by PiotrMachowski** [comment]
Fixed in v1.0.2
